server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: personal
    password: personal
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.intelligent.marking.intelligentmarking.entity
roll:
  appid: vpuilepmsqqevjus
  appsecret: ABSOdoBaIhc6x1hgTlrQk4DbaePPDGTb
# urls
news:
  neteasy:
    url: http://news.163.com/
  toutiao:
    url: https://www.toutiao.com/ch/news_hot/
  sohu:
    url: http://news.sohu.com/
  ifeng:
    url: http://www.ifeng.com/
# logging
logging:
  level:
    root: info
